<?php
require_once ('Pokemon.php');
require_once ('Flyer.php');
/**
 * Created by PhpStorm.
 * User: Jithin Jose
 * Date: 2019-09-16
 * Time: 10:33 AM
 */

class Pidgey extends Pokemon implements Flyer
{

    private $isFlying;
    private $speed;
    private $direction;

    public function __construct($weight, $hP, $latitude, $longitude)
    {
        parent::__construct("Pidgey", "pidgey.png", $weight, $hP, $latitude, $longitude, 'flying');
        //$this->isFlying=$isFlying;
        //$this->direction=$direction;
        //$this->speed=$speed;
    }

    /**
     * @return mixed
     */
    public function getSpeed()
    {
        return $this->speed;
    }

    /**
     * @param mixed $speed
     */
    public function setSpeed($speed)
    {
        $this->speed = $speed;
    }

    /**
     * @return mixed
     */
    public function getDirection()
    {
        return $this->direction;
    }

    /**
     * @param mixed $direction
     */
    public function setDirection($direction)
    {
        $this->direction = $direction;
    }

    public function setFlying($isFlying)
    {
        $this->isFlying=$isFlying;
    }

    public function getFlying() {
        return $this->isFlying;
    }

    public function takeOff()
    {
        // TODO: Implement takeOff() method.
    }
    public function land()
    {
        // TODO: Implement land() method.
    }

    public function getDamage()
    {
        return $this->getWeight()*0.4;
    }
    public function attack(Pokemon $poke)
    {
        parent::attack($poke); // TODO: Change the autogenerated stub
    }


}